import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import SideNav from "./side-nav";

export const metadata: Metadata = {
  title: "Indigenous Business Intelligence",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/itc.jpeg" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        {/* grid layout of 2 columns, the left column is the sidebar of width 16rem, and the main content will take up the remaining space */}
        <div className="grid h-full grid-cols-[16rem_1fr]">
          <SideNav />
          <main className="p-4 overflow-y-auto">{children}</main>
        </div>
      </body>
    </html>
  );
}
