import "~/styles/globals.css";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import SideNav from "./side-nav";
import { Toaster } from "~/components/ui/sonner"

export const metadata: Metadata = {
  title: "Indigenous Business Intelligence",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/itc.jpeg" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <div className="grid h-full grid-cols-[16rem_1fr]">
          <SideNav />
          <main className="overflow-y-auto">{children}</main>
          <Toaster />
        </div>
      </body>
    </html>
  );
}
